Class {
	#name : #AbstractNavigationPage,
	#superclass : #AbstractPage,
	#category : #'SqueakLanguageLearning-Pages'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'EB 6/3/2024 00:11'
}
AbstractNavigationPage class >> newWithWithController: aController [

	^super basicNew initializeWithController: aController
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'Alexander Netz 6/7/2024 21:59'
}
AbstractNavigationPage >> initializeWithController: aController [
	super initializeWithController: aController.
	
	

]
