Class {
	#name : #SLGExercisePage,
	#superclass : #SLGSubPage,
	#instVars : [
		'exercise'
	],
	#category : #SqueakLanguageLearning
}

{
	#category : #accessing,
	#'squeak_changestamp' : 'xiaoshi 5/26/2024 14:23'
}
SLGExercisePage >> exercise [
	^ exercise
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'xiaoshi 5/26/2024 14:23'
}
SLGExercisePage >> exercise: anObject [
	exercise := anObject
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'xiaoshi 5/28/2024 10:23'
}
SLGExercisePage >> initialize [
	
	super initialize.
]
